apiVersion: v1
kind: Service
metadata:
  name: pro-dw-service
  namespace: gitlab-uaim
spec:
  selector:
    app: pro-dw
  type: LoadBalancer
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
      nodePort: 30081