version: "3.9"
services:
  
  doctors:
    build:
      context: ./Doctors
    ports:
      - "8082:80"
    depends_on: 
      - "doctors_db"

  rooms:
    build:
      context: ./ExaminationRooms
    ports:
      - "8081:80"
    depends_on:
      - "rooms_db"
    environment:
      EXM_ROOM_ConnectionStrings__MyConnection: "Server=rooms_db;Database=master;User=sa;Password=zaq1@WSX;"

  roomselector:
    build:
      context: ./ExaminationRoomsSelector
    ports:
      - "8080:80"
    environment:
      EXM_ROOM_SEL_ServiceConfiguration__DoctorUrl: "http://doctors/"
      EXM_ROOM_SEL_ServiceConfiguration__RoomUrl: "http://rooms/"

  doctors_db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      SA_PASSWORD: "zaq1@WSX"
      ACCEPT_EULA: "Y"
#    ports:
#      - "1433:1433"
    volumes:
      - ./Doctors/init.sql:/init.sql
      - ./Doctors/setup.sh:/setup.sh
      - ./Doctors/entrypoint.sh:/entrypoint.sh
    command: /bin/bash ./entrypoint.sh

  rooms_db:
    image: "mcr.microsoft.com/mssql/server"
    restart: always
    ports:
      - "1434:1433"
    volumes:
      - ./ExaminationRooms/init.sql:/init.sql
      - ./ExaminationRooms/setup.sh:/setup.sh
      - ./ExaminationRooms/entrypoint.sh:/entrypoint.sh
    environment:
      SA_PASSWORD: "zaq1@WSX"
      ACCEPT_EULA: "Y"
    command: /bin/bash ./entrypoint.sh
    