version: "3.9"
services:
  rooms:
    build:
      context: ./ExaminationRooms

  roomselector:
    build:
      context: ./ExaminationRoomsSelector
    ports:
      - "8080:80"

  doctors:
    build:
      context: ./Doctors
