version: "3.9"
services:

  doctors-data:
    image: "dadurex/uaim_lab_doctors_data"
    ports:
      - "8082:80"
    environment:
      DOCTOR_ConnectionStrings__MyConnection: "Server=doctors-db;Database=master;User=sa;Password=zaq1@WSX;"
      
  rooms-data:
    image: "dadurex/uaim_lab_rooms_data"
    ports:
      - "8081:80"
    environment:
      EXM_ROOM_ConnectionStrings__MyConnection: "Server=rooms-db;Database=master;User=sa;Password=zaq1@WSX;"

  roomselector-app:
    image: "dadurex/uaim_lab_roomselector_app"
    ports:
      - "44328:80"
    environment:
      EXM_ROOM_SEL_ServiceConfiguration__DoctorUrl: "http://doctors-data/"
      EXM_ROOM_SEL_ServiceConfiguration__RoomUrl: "http://rooms-data/"
      
  web-app:
    image: "dadurex/uaim_lab_web_app"
    ports:
      - "42069:80"
    environment:
      WEB_APP_ServiceConfiguration__BackendUrl: "http://roomselector-app/"