version: "3.9"
services:
  doctors:
    build:
      context: ./Doctors
    ports:
      - "8082:80"
    depends_on: 
      - "doctors_db"
       
  rooms:
    build:
      context: ./ExaminationRooms
    ports:
      - "8081:80"
    depends_on:
      - "rooms_db"
 
  roomselector:
    build:
      context: ./ExaminationRoomsSelector
    ports:
      - "8080:80"
        
  doctors_db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      SA_PASSWORD: "123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
     
  rooms_db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      SA_PASSWORD: "123"
      ACCEPT_EULA: "Y"

    
