version: "3.9"
services:

  doctors-data:
    image: "dadurex/uaim_lab_doctors_data"
    ports:
      - "8082:80"
    depends_on:
      - "doctors-db"
    environment:
      DOCTOR_ConnectionStrings__MyConnection: "Server=doctors-db;Database=master;User=sa;Password=zaq1@WSX;"
      
  rooms-data:
    image: "dadurex/uaim_lab_rooms_data"
    ports:
      - "8081:80"
    depends_on:
      - "rooms-db"
    environment:
      EXM_ROOM_ConnectionStrings__MyConnection: "Server=rooms-db;Database=master;User=sa;Password=zaq1@WSX;"

  roomselector-app:
    image: "dadurex/uaim_lab_roomselector_app"
    ports:
      - "44328:80"
    environment:
      EXM_ROOM_SEL_ServiceConfiguration__DoctorUrl: "http://doctors-data/"
      EXM_ROOM_SEL_ServiceConfiguration__RoomUrl: "http://rooms-data/"

  doctors-db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      SA_PASSWORD: "zaq1@WSX"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - ./DoctorsData/DoctorsData.Web/Database/init.sql:/init.sql
      - ./DoctorsData/DoctorsData.Web/Database/setup.sh:/setup.sh
      - ./DoctorsData/DoctorsData.Web/Database/entrypoint.sh:/entrypoint.sh
    command: /bin/bash ./entrypoint.sh    
    
  rooms-db:
    image: "mcr.microsoft.com/mssql/server"
    restart: always
    ports:
      - "1434:1433"
    volumes:
      - ./ExaminationRoomsData/ExaminationRoomsData.Web/Database/init.sql:/init.sql
      - ./ExaminationRoomsData/ExaminationRoomsData.Web/Database/setup.sh:/setup.sh
      - ./ExaminationRoomsData/ExaminationRoomsData.Web/Database/entrypoint.sh:/entrypoint.sh
    environment:
      SA_PASSWORD: "zaq1@WSX"
      ACCEPT_EULA: "Y"
    command: /bin/bash ./entrypoint.sh