apiVersion: apps/v1
kind: Deployment
metadata:
  name: pro-dd-deployment
  namespace: gitlab-uaim
  labels:
    app: pro-dd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pro-dd
  template:
    metadata:
      labels:
        app: pro-dd
    spec:
      containers:
        - name: pro-dd
          image: roundel/uaim_lab_doctors-data
          imagePullPolicy: Always
          ports:
            - containerPort: 80