apiVersion: apps/v1
kind: Deployment
metadata:
  name: doctors-data
spec:
  replicas: 1
  selector:
    matchLabels:
      app: doctors-data
  template:
    metadata:
      labels:
        app: doctors-data
    spec:
      containers:
        - name: doctors-data
          image: roundel/uaim_lab_doctors-data
          imagePullPolicy: Always
          ports:
            - containerPort: 80