apiVersion: apps/v1
kind: StatefulSet 
metadata:
  name: pro-dd-statefulset
  namespace: gitlab-uaim
  labels:
    app: pro-dd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pro-dd
  serviceName: pro-dd-service
  template:
    metadata:
      labels:
        app: pro-dd
    spec:
      containers:
        - name: pro-dd
          image: roundel/uaim_project_doctors-data
          imagePullPolicy: Always
          ports:
            - containerPort: 80