apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapplication
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapplication
  template:
    metadata:
      labels:
        app: webapplication
    spec:
      containers:
        - name: webapplication
          image: dadurex/uaim_project_patients_web
          imagePullPolicy: Always
          ports:
            - containerPort: 80