apiVersion: v1
kind: Service
metadata:
  name: pro-pw-service
  namespace: gitlab-uaim
spec:
  selector:
    app: pro-pw
  type: LoadBalancer
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
      nodePort: 30080