apiVersion: v1
kind: Service
metadata:
  name: patients-web
  namespace: uaim
spec:
  selector:
    app: patients-web
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 30080
