version: "3.9"
services:
  doctors-data:
    image: roundel/uaim_project_doctors-data
    ports:
      - "5004:80"

  patients-data:
    image: dadurex/uaim_project_patients_data
    ports:
      - "5000:80"

  doctors-app:
    image: dadurex/uaim_project_doctors_app
    environment:
      DOC_APP_ServiceConfiguration__DoctorsDataUrl: "http://doctors-data"
      DOC_APP_ServiceConfiguration__PatientsDataUrl: "http://patients-data"

  patients-app:
    image: roundel/uaim_project_patients-app
    environment:
      PAT_APP_ServiceConfiguration__DoctorsDataUrl: "http://doctors-data"
      PAT_APP_ServiceConfiguration__PatientsDataUrl: "http://patients-data"
    ports:
      - "42070:80"
      
  patients-web:
    image: dadurex/uaim_project_patients_web
    ports:
      - "8080:80"