apiVersion: apps/v1
kind: Deployment
metadata:
  name: patients-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: patients-app
  template:
    metadata:
      labels:
        app: patients-app
    spec:
      containers:
        - name: patients-app
          image: roundel/uaim_project_patients-app
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: PAT_APP_ServiceConfiguration__DoctorsDataUrl
              value: "http://doctors-data"
            - name: PAT_APP_ServiceConfiguration__PatientsDataUrl
              value: "http://patients-data"
