apiVersion: apps/v1
kind: Deployment
metadata:
  name: patients-data
spec:
  replicas: 1
  selector:
    matchLabels:
      app: patients-data
  template:
    metadata:
      labels:
        app: patients-data
    spec:
      containers:
        - name: patients-data
          image: dadurex/uaim_project_patients_data
          imagePullPolicy: Always
          ports:
            - containerPort: 80