apiVersion: apps/v1
kind: Deployment
metadata:
  name: doctors-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: doctors-app
  template:
    metadata:
      labels:
        app: doctors-app
    spec:
      containers:
        - name: doctors-app
          image: dadurex/uaim_project_doctors_app
          imagePullPolicy: Always
          ports:
            - containerPort: 80