apiVersion: apps/v1
kind: Deployment
metadata:
  name: pro-da-deployment
  namespace: gitlab-uaim
  labels:
    app: pro-da
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pro-da
  template:
    metadata:
      labels:
        app: pro-da
    spec:
      containers:
        - name: pro-da
          image: dadurex/uaim_project_doctors_app
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: DOC_APP_ServiceConfiguration__DoctorsDataUrl
              value: http://pro-dd-service
            - name: DOC_APP_ServiceConfiguration__PatientsDataUrl
              value: http://pro-pd-service    