version: "3.9"
services:

  doctors-data:
    image: dadurex/uaim_lab_doctors_data
    depends_on:
      - "doctors-db"
    environment:
      DOCTOR_ConnectionStrings__MyConnection: "Server=doctors-db;Database=master;User=sa;Password=zaq1@WSX;"

  rooms-data:
    image: dadurex/uaim_lab_rooms_data
    depends_on:
      - "rooms-db"
    environment:
      EXM_ROOM_ConnectionStrings__MyConnection: "Server=rooms-db;Database=master;User=sa;Password=zaq1@WSX;"

  roomselector-app:
    image: dadurex/uaim_lab_roomselector_app
    ports:
      - "44328:80"
    environment:
      EXM_ROOM_SEL_ServiceConfiguration__DoctorUrl: "http://doctors-data/"
      EXM_ROOM_SEL_ServiceConfiguration__RoomUrl: "http://rooms-data/"

  doctors-db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      SA_PASSWORD: "zaq1@WSX"
      ACCEPT_EULA: "Y"
    volumes:
      - ../../Laboratorium/DoctorsData/DoctorsData.Web/Database/init.sql:/init.sql
      - ../../Laboratorium/DoctorsData/DoctorsData.Web/Database/setup.sh:/setup.sh
      - ../../Laboratorium/DoctorsData/DoctorsData.Web/Database/entrypoint.sh:/entrypoint.sh
    command: /bin/bash ./entrypoint.sh

  rooms-db:
    image: "mcr.microsoft.com/mssql/server"
    restart: always
    volumes:
      - ../../Laboratorium/ExaminationRoomsData/ExaminationRoomsData.Web/Database/init.sql:/init.sql
      - ../../Laboratorium/ExaminationRoomsData/ExaminationRoomsData.Web/Database/setup.sh:/setup.sh
      - ../../Laboratorium/ExaminationRoomsData/ExaminationRoomsData.Web/Database/entrypoint.sh:/entrypoint.sh
    environment:
      SA_PASSWORD: "zaq1@WSX"
      ACCEPT_EULA: "Y"
    command: /bin/bash ./entrypoint.sh