variables:
  OBJECTS_DIRECTORY: 'obj'
  NUGET_PACKAGES_DIRECTORY: '.nuget'
  SOURCE_CODE_PATH: 'Projekt/DoctorsApp'

default:
  before_script:
    - cd $SOURCE_CODE_PATH

stages:
#  - build
#  - test
#  - publish
  - deploy

workflow:
  rules:
    - if: $CI_MERGE_REQUEST_IID
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

build:
  stage: build
  image: mcr.microsoft.com/dotnet/sdk:5.0
  script:
    - dotnet restore
    - dotnet build

test:
  stage: test
  image: mcr.microsoft.com/dotnet/sdk:5.0
  script:
    - dotnet restore
    - dotnet test

publish:
  stage: publish
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [ "" ]
  script:
    - 'mkdir -p /kaniko/.docker'
    - 'echo "{\"auths\":{ $REGISTRY_AUTH }}" > /kaniko/.docker/config.json'
    - '/kaniko/executor --dockerfile Dockerfile --destination $PATIENTS_WEB_IMAGE:latest'
  only:
    - master

deploy:
  stage: deploy
  image: bitnami/kubectl
  script:
    - kubectl config set-cluster k8s --server=https://$KUBE_HOST:5000 --certificate-authority=$KUBE_API_CERT
    - kubectl config set-credentials k8s-deployer --token=$KUBE_API_TOKEN
    - kubectl config set-context k8s --cluster k8s --user k8s-deployer
    - kubectl config use-context k8s
    - kubectl apply -f "/builds/$CI_PROJECT_PATH/Miniprojekty/Kubernetes/PatientsWebApp"