variables:
  OBJECTS_DIRECTORY: 'obj'
  NUGET_PACKAGES_DIRECTORY: '.nuget'
  SOURCE_CODE_PATH: 'Projekt/DoctorsApp'

default:
  before_script:
    - cd $SOURCE_CODE_PATH

stages:
  - deploy

deploy:
  stage: deploy
  image: 
    name: bitnami/kubectl
    entrypoint: [ "" ]
  before_script:
    - 'pwd'
    - 'export KUBECONFIG=/etc/kubernetes/kubelet.conf'
    - 'cat $K8S_CONFIG'
    - 'cat $K8S_CONFIG | base64 -d > ${KUBECONFIG}'
    - 'cat $KUBECONFIG'
    - 'ls -la'
    - 'echo $CI_PROJECT_PATH'
  script:
    - 'kubectl cluster-info'
    - 'kubectl apply -f /builds/$CI_PROJECT_PATH/Miniprojekty/Kubernetes/PatientsWebApp'
    - 'kubectl rollout restart deployment patients-web'