variables:
  OBJECTS_DIRECTORY: 'obj'
  NUGET_PACKAGES_DIRECTORY: '.nuget'
  SOURCE_CODE_PATH: 'Projekt/DoctorsApp'

default:
  before_script:
    - cd $SOURCE_CODE_PATH

stages:
  - deploy

deploy:
  stage: deploy
  image: bitnami/kubectl
  script:
    - kubectl config set-cluster k8s --server=https://$KUBE_HOST:5000 --certificate-authority=$KUBE_API_CERT
    - kubectl config set-credentials k8s-deployer --token=$KUBE_API_TOKEN
    - kubectl config set-context k8s --cluster k8s --user k8s-deployer
    - kubectl config use-context k8s
    - kubectl apply -f "/builds/$CI_PROJECT_PATH/Miniprojekty/Kubernetes/PatientsWebApp"