variables:
  OBJECTS_DIRECTORY: 'obj'
  NUGET_PACKAGES_DIRECTORY: '.nuget'
  SOURCE_CODE_PATH: 'Projekt/DoctorsApp'

default:
  before_script:
    - cd $SOURCE_CODE_PATH

stages:
  - deploy

deploy:
  stage: deploy
  #image: bitnami/kubectl
  before_script:
    - 'cat ${K8S_CONFIG}'
    - 'cat ${KUBECONFIG}'
    - 'echo workingg'
    - 'echo ${K8S_CONFIG} > $KUBECONFIG'
  script:
    - 'echo scripts'
#    - 'kubectl apply -f /builds/$CI_PROJECT_PATH/Miniprojekty/Kubernetes/PatientsWebApp'
#    - 'kubectl rollout restart deployment patients-web'