variables:
  OBJECTS_DIRECTORY: 'obj'
  NUGET_PACKAGES_DIRECTORY: '.nuget'
  SOURCE_CODE_PATH: 'Projekt/DoctorsApp'

default:
  before_script:
    - cd $SOURCE_CODE_PATH

stages:
  - deploy

deploy:
  stage: deploy
  image: 
    name: bitnami/kubectl
    entrypoint: [ "" ]
  before_script:
    - 'pwd'
    - 'ls -la'
    - 'touch ~/.kube/config'
    - 'echo ${K8S_CONFIG} > ~/.kube/config'
  script:
    - 'kubectl apply -f /builds/$CI_PROJECT_PATH/Miniprojekty/Kubernetes/PatientsWebApp'
    - 'kubectl rollout restart deployment patients-web'