variables:
  OBJECTS_DIRECTORY: 'obj'
  NUGET_PACKAGES_DIRECTORY: '.nuget'
  SOURCE_CODE_PATH: 'Projekt/DoctorsApp'

default:
  before_script:
    - cd $SOURCE_CODE_PATH

stages:
  - deploy

deploy:
  stage: deploy
  image: 
    name: bitnami/kubectl
    entrypoint: [ "" ]
  before_script:
    - 'pwd'
    - 'ls'
    - 'export KUBECONFIG=$(mktemp)'
    - 'ls'
    - 'echo ${K8S_CONFIG}'
    - 'echo ${K8S_CONFIG} | base64 -d > ${KUBECONFIG}'
    - 'pwd'
    - 'ls'


  script:
    - 'kubectl apply -f /builds/$CI_PROJECT_PATH/Miniprojekty/Kubernetes/PatientsWebApp'
    - 'kubectl rollout restart deployment patients-web'